import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  weight: ["400"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Cometalk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased bg-gray-100 bg-[url('/background.jpg')] bg-contain bg-fixed`}
      >
        <Toaster></Toaster>
        {children}
      </body>
    </html>
  );
}
